<script>
  import { onMount } from 'svelte';

  // When the component mounts, we'll find the TOC generated by rehype-toc
  // and display it in our sidebar
  onMount(() => {
    const tocElement = document.querySelector('.toc');
    const container = document.querySelector('.toc-container');
    
    if (tocElement && container) {
      container.appendChild(tocElement);
      
      // After TOC is added to the container, implement scroll highlighting
      setTimeout(setupScrollHighlighting, 200);
    }
  });
  
  function setupScrollHighlighting() {
    const tocLinks = document.querySelectorAll('.toc-container a');
    if (!tocLinks.length) return;
    
    // Get all section headings from the document
    const sections = [];
    tocLinks.forEach(link => {
      const href = link.getAttribute('href');
      if (href && href.startsWith('#')) {
        const id = href.substring(1); // Remove the # at the beginning
        const section = document.getElementById(id);
        if (section) {
          sections.push({
            id,
            section,
            link
          });
        }
      }
    });
    
    // Function to update active section
    function updateActiveSection() {
      let activeSection = null;
      
      // Find which section is currently in view
      for (const {id, section, link} of sections) {
        const rect = section.getBoundingClientRect();
        // Check if section is in view (top of section is above the middle of the viewport)
        if (rect.top <= 150) {
          activeSection = {id, section, link};
        } else {
          // If we've passed the section that's in view, break
          break;
        }
      }
      
      // Remove active class from all links
      tocLinks.forEach(link => link.classList.remove('active'));
      
      // Add active class to the active section's link
      if (activeSection) {
        activeSection.link.classList.add('active');
      } else if (sections.length > 0) {
        // If no section is active, highlight the first
        sections[0].link.classList.add('active');
      }
    }
    
    // Update active section on scroll
    window.addEventListener('scroll', updateActiveSection, { passive: true });
    
    // Initial update
    updateActiveSection();
  }
</script>

<div class="toc-container">
  <h3 class="text-lg font-semibold mb-4">On this page</h3>
</div>

<style>
  .toc-container :global(.toc nav) {
    position: sticky;
    top: 2rem;
    max-height: calc(100vh - 4rem);
    overflow-y: auto;
  }
  
  .toc-container :global(.toc ul) {
    list-style-type: none;
    padding-left: 0;
    margin-top: 0.5rem;
  }
  
  .toc-container :global(.toc li) {
    margin-bottom: 0.5rem;
  }
  
  .toc-container :global(.toc a) {
    text-decoration: none;
    transition: color 0.2s, background-color 0.2s;
    font-size: 0.875rem;
    line-height: 1.25rem;
    display: block;
    padding: 0.25rem 0.5rem;
    border-radius: 0.25rem;
    font-weight: 300;
  }
  
  .toc-container :global(.toc a:hover) {
    font-weight: 700;
  }
  
  .toc-container :global(.toc a.active) {
    font-weight: 600;
  }
  
  .toc-container :global(ol) {
    padding-left: 0.5rem;
    margin-top: 0.5rem;
  }
</style> 