<script>
  import { onMount } from 'svelte';

  // When the component mounts, we'll find the TOC generated by rehype-toc
  // and display it in our sidebar
  onMount(() => {
    const tocElement = document.querySelector('.toc');
    const container = document.querySelector('.toc-container');
    
    if (tocElement && container) {
      container.appendChild(tocElement);
    }
  });
</script>

<div class="toc-container">
  <h3 class="text-lg font-semibold mb-4">On this page</h3>
</div>

<style>
  .toc-container :global(.toc nav) {
    position: sticky;
    top: 2rem;
    max-height: calc(100vh - 4rem);
    overflow-y: auto;
  }
  
  .toc-container :global(.toc ul) {
    list-style-type: none;
    padding-left: 0;
    margin-top: 0.5rem;
  }
  
  .toc-container :global(.toc li) {
    margin-bottom: 0.5rem;
  }
  
  .toc-container :global(.toc a) {
    color: #718096;
    text-decoration: none;
    transition: color 0.2s;
    font-size: 0.9rem;
  }
  
  .toc-container :global(.toc a:hover) {
    color: #2d3748;
    text-decoration: underline;
  }
  
  .toc-container :global(.toc ul ul) {
    padding-left: 1rem;
    margin-top: 0.5rem;
  }
</style> 